



-- 테이블 생성
CREATE TABLE KH_STUDENT(
	STD_NO NUMBER PRIMARY KEY,
	STD_NAME NVARCHAR2(5) NOT NULL,
	STD_AGE NUMBER NOT NULL,
	MAJOR NVARCHAR2(10) NOT NULL,
	ENT_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM KH_STUDENT;

COMMENT ON COLUMN KH_STUDENT.STD_NO   	  IS '학생번호';
COMMENT ON COLUMN KH_STUDENT.STD_NAME  	  IS '학생이름';
COMMENT ON COLUMN KH_STUDENT.STD_AGE  	  IS '학생나이';
COMMENT ON COLUMN KH_STUDENT.MAJOR    	  IS '학과';
COMMENT ON COLUMN KH_STUDENT.ENT_DATE  	  IS '입학일';

CREATE SEQUENCE SEQ_STD_NO NOCACHE;

INSERT INTO KH_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL,'김하나','20','건축학과',DEFAULT);
INSERT INTO KH_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL,'차두리','24','생명공학과',DEFAULT);
INSERT INTO KH_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL,'이영표','22','기계공학과',DEFAULT);
INSERT INTO KH_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL,'손흥민','28','전자공학과',DEFAULT);
INSERT INTO KH_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL,'이강인','21','전자공학과',DEFAULT);
INSERT INTO KH_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL,'황희찬','20','체육학과',DEFAULT);


UPDATE KH_STUDENT 
SET STD_NAME = '호날두',
STD_AGE = '30',
MAJOR = '체육학과'
WHERE STD_NO = '7';


